# Generated by Django 3.2.7 on 2022-03-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fitness',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=1000)),
                ('link', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='yoga',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=1000)),
                ('link', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
