# Generated by Django 3.2.7 on 2022-03-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='cricket',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='fitness',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='football',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='yoga',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
