# Generated by Django 3.2.7 on 2022-03-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_auto_20220312_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='cricket',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cricket',
            name='sports_type',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='fitness',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fitness',
            name='sports_type',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='football',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='football',
            name='sports_type',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='yoga',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yoga',
            name='sports_type',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
