# Generated by Django 3.2.7 on 2022-03-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_auto_20220312_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='allvideos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=1000)),
                ('description', models.CharField(default='', max_length=1000)),
                ('link', models.CharField(default='', max_length=1000)),
                ('sports_type', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=1000)),
                ('weight', models.CharField(default='', max_length=1000)),
                ('photo', models.ImageField(blank=True, upload_to='events/')),
                ('age', models.IntegerField(default=0)),
                ('sports', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='timestamp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.CharField(default='', max_length=1000)),
                ('completed', models.BooleanField(default=False)),
                ('title', models.CharField(default='', max_length=1000)),
                ('link', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
