export const allData = [
    {
      id: 1,
      title: 'Cover Drive',
      videoLink: 'https://youtu.be/fELk4k1pndg',
      completed: true,
      sport: 'cricket',
      type: 'batting',
    },
    {
      id: 2,
      title: 'Grip and Stance',
      videoLink: 'https://youtu.be/gusv3BsHd3g',
      completed: false,
      sport: 'cricket',
      type: 'batting',
    },
    {
      id: 3,
      title: 'Backlist and Footwork',
      videoLink: 'https://youtu.be/7SBYgRCk9bg',
      completed: false,
      sport: 'cricket',
      type: 'batting',
    },
    {
      id: 4,
      title: 'Front Foot Defence',
      videoLink: 'https://youtu.be/CdlYCoqUVEQ',
      completed: false,
      sport: 'cricket',
      type: 'batting',
    },
    {
      id: 5,
      title: 'Bowl Good Length',
      videoLink: 'https://youtu.be/K_2W3cFSk14',
      completed: true,
      sport: 'cricket',
      type: 'balling',
    },
    {
      id: 6,
      title: 'Bowl Good Length',
      videoLink: 'https://youtu.be/K_2W3cFSk14',
      completed: false,
      sport: 'cricket',
      type: 'balling',
    },
    {
      id: 7,
      title: 'Bowl Good Length',
      videoLink: 'https://youtu.be/K_2W3cFSk14',
      completed: false,
      sport: 'cricket',
      type: 'balling',
    },
    {
      id: 8,
      title: 'Bowl Good Length',
      videoLink: 'https://youtu.be/K_2W3cFSk14',
      completed: false,
      sport: 'cricket',
      type: 'balling',
    },
    {
      id: 9,
      title: 'Catching Drills ',
      videoLink: 'https://youtu.be/K_2W3cFSk14',
      completed: true,
      sport: 'cricket',
      type: 'feilding',
    },
    {
      id: 10,
      title: 'Catching Drills ',
      videoLink: 'https://youtu.be/K_2W3cFSk14',
      completed: false,
      sport: 'cricket',
      type: 'feilding',
    },
    {
      id: 11,
      title: 'Catching Drills ',
      videoLink: 'https://youtu.be/K_2W3cFSk14',
      completed: false,
      sport: 'cricket',
      type: 'feilding',
    },
    {
      id: 12,
      title: 'Catching Drills ',
      videoLink: 'https://youtu.be/eCRqTPUjsCA',
      completed: false,
      sport: 'cricket',
      type: 'feilding',
    },
  ];
  